name = "head-start"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2026-07-03"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true
