/**
 * Maps DatoCMS GraphQL __typename to their corresponding model API keys.
 * Used to construct editor URLs for preview mode.
 * 
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by scripts/generate-model-api-keys.ts
 * Run 'npm run prep:generate-model-api-keys' to regenerate.
 */
export const DATOCMS_MODEL_API_KEY_MAP: Record<string, string> = {
  'ActionBlockRecord': 'action_block',
  'AppRecord': 'app',
  'EmailLinkRecord': 'email_link',
  'EmbedBlockRecord': 'embed_block',
  'ExternalLinkRecord': 'external_link',
  'FileRecord': 'file',
  'GroupingBlockRecord': 'grouping_block',
  'GroupingItemRecord': 'grouping_item',
  'HomePageRecord': 'home_page',
  'ImageBlockRecord': 'image_block',
  'InternalLinkRecord': 'internal_link',
  'MenuItemInternalRecord': 'menu_item_internal',
  'NotFoundPageRecord': 'not_found_page',
  'PagePartialBlockRecord': 'page_partial_block',
  'PagePartialRecord': 'page_partial',
  'PageRecord': 'page',
  'PhoneLinkRecord': 'phone_link',
  'RedirectRuleRecord': 'redirect_rule',
  'SchemaMigrationRecord': 'schema_migration',
  'TableBlockRecord': 'table_block',
  'TextBlockRecord': 'text_block',
  'TextImageBlockRecord': 'text_image_block',
  'TranslationRecord': 'translation',
  'VideoBlockRecord': 'video_block',
  'VideoEmbedBlockRecord': 'video_embed_block',
  'VideoTextTrackRecord': 'video_text_track',
} as const;
  
/**
 * Gets the DatoCMS model API key from a GraphQL __typename.
 */
export function getModelApiKey(typename: string | undefined, fallback = 'page'): string {
  if (!typename) return fallback;
  return DATOCMS_MODEL_API_KEY_MAP[typename] || fallback;
}
