import { buildClient } from '@datocms/cma-client-node';
import dotenv from 'dotenv-safe';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { datocmsEnvironment } from '../datocms-environment';

dotenv.config({
  allowEmptyValues: Boolean(process.env.CI),
});

/**
 * Converts a model API key (e.g., 'home_page') to GraphQL __typename format (e.g., 'HomePageRecord').
 */
function toTypename(apiKey: string): string {
  const pascalCase = apiKey
    .split(/[_-]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
  return `${pascalCase}Record`;
}

/**
 * Generates the modelApiKeys.ts file from DatoCMS item types.
 * This ensures the mapping stays in sync with the actual models in DatoCMS.
 */
async function generateModelApiKeys() {
  const token = process.env.DATOCMS_API_TOKEN?.trim();
  if (!token) {
    if (process.env.CI) {
      console.log(
        'DATOCMS_API_TOKEN is missing; skipping model API key generation.',
      );
      return;
    }
    throw new Error(
      'DATOCMS_API_TOKEN is required to generate model API keys. Set it and rerun `npm run prep:generate-model-api-keys`.',
    );
  }

  const client = buildClient({
    apiToken: token,
    environment: datocmsEnvironment,
  });

  const itemTypes = await client.itemTypes.list();
  const models = itemTypes.filter((itemType) => {
    return itemType.api_key;
  });

  const mappings = models
    .map((itemType) => {
      if (!itemType.api_key) return null;
      const typename = toTypename(itemType.api_key);
      return `  '${typename}': '${itemType.api_key}',`;
    })
    .filter(Boolean)
    .sort();

  const fileContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by scripts/generate-model-api-keys.ts
 */
export const DATOCMS_MODEL_API_KEY_MAP: Record<string, string> = {
${mappings.join('\n')}
} as const;

export function getModelApiKey(typename: string | undefined): string | null {
  if (!typename) return null;
  return DATOCMS_MODEL_API_KEY_MAP[typename] ?? null;
}
`;

  const filePath = './src/lib/datocms/modelApiKeys.ts';
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, fileContent);

  console.log('Model API keys generated');
}

generateModelApiKeys()
  .catch((error) => {
    console.error('Failed to generate model API keys:', error);
    process.exit(1);
  });
